---
title: 'Линейный корабль Principe de Asturias'
author: ''
encoding: 'utf-8'   
date: '2021-01-01'
tags:
draft: no
---
«Príncipe de Asturias» — 112-пушечный трехпалубный линейный корабль Королевской Армады Испании (1794-1817). Серия «Santa Ana».

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(kableExtra)
library(readxl)
df <- read_xlsx("dimensions.xlsx")
kbl(df, align='c', caption = "Характеристики на 1805 год") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

## История корабля

«Príncipe de Asturias» построен по проекту инженера Хосе Ромеро Фернандеса де Ланды и назван в честь Фердинанда VII, принца Астурийского и будущего короля Испании. Корабль был спущен на воду 28 января 1794 года в порту Гаваны. После завершения всех работ по вооружению он отправился на свою постоянную испанскую базу в Кадисе, сопровождая богатый торговый караван на пути через Атлантику.

Первое путешествие «Príncipe» оказалось крайне неудачным — 34 члена экипажа погибли, еще 30 остались в госпиталях. Его капитан, дон Адриан Валькарсель, жаловался на ужасное состояние судна — он считал, что строители слишком спешили спустить корабль на воду и не успели подготовить его к плаванию через океан.

> … балласт распределен отвратительно, нет должной осадки, слишком короткий такелаж для таких высоких мачт, офицеры идиоты, в команде нет ни марсового, ни гардемаринов, большая часть экипажа — негры и мулаты…

Матросы, набранные на Карибских островах, привыкли к местному теплому климату и не были готовы к тяжелому февральскому переходу в сезон сильных холодных ветров. Люди быстро становились жертвами голода, акклиматизации и отсутствия необходимой медицинской помощи — на корабле не было достаточных запасов продовольствия и лекарств. Капитан искренне удивлялся, что в таких ужасных условиях неопытные моряки, видевшие, как волны поглощают тела их погибших соратников, продолжают честно исполнять свой долг и не дают ни малейшего повода для наказания. Наконец, после длительных месяцев мучений «Príncipe» зашел в порт Кадиса 17 мая 1795 года. Отчет, отправленный Валькарселем в министерство, остался без какого-либо внимания и на долгие годы затерялся в огромных архивах.

19 января 1796 года испанский фрегат «Sabina» под командованием Якова Стюарта (потомка Якова I) столкнулся с британской «Minerve» Нельсона. Через три часа упорного сопротивления испанский корабль сдался, однако ему на помощь пришел «Príncipe de Asturias». Британцы сбежали, забрав с собой раненого Стюарта и оставив на борту фрегата Томаса Харди, командира «Victory» при Трафальгаре, и еще 40 своих моряков. В 1797 году пленников обменяли.

В битве при Сан-Висенте в 1797 «Príncipe de Asturias» был флагманом адмирала Морено под командованием коммодора Эсканьо. Корабль шел в арьергарде и находился на приличном удалении от основных сил испанцев, но в критический момент ему удалось защитить сильно поврежденную «Santísima Trinidad» от захвата, а также спасти «Purícima Concepción» и «Mejicano». Из отчета Эсканьо:

> Принимая во внимание все факты, могу сказать без лишней скромности, что состояние беспорядка и паники из-за неожиданной атаки неприятеля стало бы критическим для основных сил нашей эскадры; они были бы разбиты, если бы «Príncipe de Asturias» не разрезал вражескую колонну напополам, отвлекая корабли их арьергарда от преследования.

В этой битве «Príncipe» потерял 10 человек убитыми и 19 ранеными. Серьезно пострадала грот-мачта — корабль потерял стеньгу и марс; также была разломана фок-рея, порваны 10 парусов и уничтожены 2 пушки.

В июле 1797 года «Príncipe» доставлял неприятности Нельсону во время нападения на Кадис. 6 февраля 1798 корабль стал флагманом Федерико Гравины под командованием коммодора Хуана Висенте Яньеса; он попытался прорваться к эскадре Массаредо, преследующей британцев, однако быстро отказался от этой затеи и вернулся в Кадис. В конце 1798 года снова пересек Атлантику, чтобы высадить войска на Карибах; в этот раз обошлось без фатальных приключений. В 1799 был блокирован в Бресте и вернулся в Кадис лишь в 1802 году.

Из Кадиса отправился в Картахену в составе эскадры «Domingo de Nava», чтобы эвакуировать королевскую семью Пармы из Италии. Во время путешествия напоролся бушпритом на «Bahama» из своего отряда и остался в Картахене для ремонта. На этот период «Príncipe» передали в командование Чурруке, который активно занялся его усовершенствованием. Иногда корабль выходил в море в качестве транспорта; король Карл IV оказал честь экипажу «Príncipe» и отправился на нем из Неаполя в Барселону в сентябре 1802 года. С 1803 по 1805 судно безвылазно находилось в порту Феррола.

В битве при Трафальгаре «Príncipe» был флагманом испанской части Объединенного флота. Кораблем командовал Рафаэль Оре; также на судне располагался штаб адмирала Гравины и вице-адмирала Эсканьо. «Príncipe» входил в состав Эскадры Наблюдения и считался кораблем резерва, однако ошибки Вильнева и Гравины подставили его под вражеский удар колонны Колинвуда. В самом конце боя флагману удалось собрать еще несколько кораблей, вырваться из-под огня и уйти в Кадис. Из-за сильного шторма он смог зайти в порт лишь 27 октября.

Длительное время корабль находился на ремонте. 9 апреля 1806 года «Príncipe» перешел под командование адмирала Игнасио де Алавы и прошел всю Войну за независимость в составе его эскадры. В 1810 году британцы приказали Верховной хунте избавиться от балласта, который требует огромных и «бессмысленных» трат на его содержание. В итоге «Príncipe» и «Santa Ana» отправились на стоянку в Гавану и больше никогда не выходили в море. Бывший могучий флагман был продан на демонтаж в 1817 году. Печальный конец одного из лучших кораблей испанского флота.